### ISSUE TITLE
这个只能适配原版吗？

### ISSUE THREAD

**Issue by wxlost** [krwu/ServerStatus-web#2]
https://github.com/ToyoDAdoubi/ServerStatus-Toyo

想给ServerStatus-Toyo换皮可惜不显示任何数据了。。。

**Comment by krwu** [comment]
我看一下toyo版的数据结构，应该可以适配的

**Comment by krwu** [comment]
> https://github.com/ToyoDAdoubi/ServerStatus-Toyo
> 
> 想给ServerStatus-Toyo换皮可惜不显示任何数据了。。。

too 版的演示地址不可用，你能提供一下可用的网址或者 stats.json 文件的示例吗？

**Comment by wxlost** [comment]
> > https://github.com/ToyoDAdoubi/ServerStatus-Toyo
> > 想给ServerStatus-Toyo换皮可惜不显示任何数据了。。。
> 
> toyo 版的演示地址不可用，你能提供一下可用的网址或者 stats.json 文件的示例吗？

http://119.28.20.171:8888/

**Comment by wxlost** [comment]
蛋疼。才发现toyo的负载 Load被改了~~难道要用原版。。。

**Comment by krwu** [comment]
> 蛋疼。才发现toyo的负载 Load被改了~~难道要用原版。。。

我用你提供的 json 数据本地运行，是可以兼容的，唯一需要处理一下的是你的数据里填充了 `name` 没有 `host`，我默认使用的是 `host` 而不是 `name`，已经做了兼容性处理，用 `name` 或者 `host` 都可以显示。

另外，地区需要写两位字母的缩写（比如 cn/hk/tw/sg/us）因为要显示为旗帜。

**Comment by wxlost** [comment]
> > 蛋疼。才发现toyo的负载 Load被改了~~难道要用原版。。。
> 
> 我用你提供的 json 数据本地运行，是可以兼容的，唯一需要处理一下的是你的数据里填充了 `name` 没有 `host`，我默认使用的是 `host` 而不是 `name`，已经做了兼容性处理，用 `name` 或者 `host` 都可以显示。
> 
> 另外，地区需要写两位字母的缩写（比如 cn/hk/tw/sg/us）因为要显示为旗帜。

明白了，感谢大佬
