### ISSUE TITLE
Question can you guys make like a better tutorial on how to set up the backend and frontend to fetch everything?

### ISSUE THREAD

**Issue by Zinedinarnaut** [krwu/ServerStatus-web#6]

**Comment by krwu** [comment]
What's your problem about setting up the ServerStatus app?

1. Deploy a ServerStatus server:  https://github.com/BotoX/ServerStatus/#master-server
2. Replace `status`  directory in previous step with my version: https://github.com/krwu/ServerStatus-web#with-release-version

If you use nginx or other web server, the root directory should point to the `status` directory.

Please leave a comment if you have any further question.
